// <auto-generated />
using System;
using CodeChallenge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeChallenge.Migrations
{
    [DbContext(typeof(CadastroCargueiroContext))]
    partial class CadastroCargueiroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CodeChallenge.Models.Cargueiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Quantidade");

                    b.Property<DateTime>("Retorno");

                    b.Property<DateTime>("Saida");

                    b.Property<int>("Tipo");

                    b.Property<string>("TipoMinerio");

                    b.HasKey("Id");

                    b.ToTable("Cargueiros");
                });
#pragma warning restore 612, 618
        }
    }
}
